### PR TITLE
fix(daemon): non-interactive permissions for agent CLIs in web UI

### LINKED ISSUE #25: 使用claude code cli时总是反复卡在申请权限这一步。
使用claude code cli时总是反复卡在申请权限这一步。

### PR DESCRIPTION
**Pull request by JoKer049**
Claude Code and other CLIs prompt for tool approval; OD has no terminal in the browser, so prompts stall the stream. Align spawn args with cwd sandboxing: Claude bypassPermissions, Codex --full-auto, Gemini/Qwen --yolo, Cursor --force.

Fixes https://github.com/nexu-io/open-design/issues/25

### CODE REVIEW

**Review by lefarcen — COMMENTED** [review]
Right diagnosis, right shape — terminal-less UI + cwd-pinned spawn means interactive-approval prompts are guaranteed to deadlock the SSE stream, so disabling them is the only sane option. Worth flagging: this PR's safety story leans entirely on the cwd sandbox holding (server.js pins cwd via `ensureProject` + `isSafeId`, which currently looks tight, and Codex `--full-auto` retains its own OS-level workspace-write sandbox). If a future change ever lets `projectId` escape the project root, every agent here gains write/exec across the host — the comment block is good, please keep it load-bearing. Cross-PR notes: PR #28 adds a Copilot adapter with `--allow-all-tools` (same posture, no conflict but should rebase on top of this); PR #15 rewrites `buildArgs` for Codex/Gemini/Cursor/Qwen to deliver the prompt via stdin and will textually conflict on every agent touched here — whichever lands second has a small but real merge to do (PR #15's `--yolo`/`--force`/`--full-auto` insertions need to be re-added). Inline notes per flag below.

File: daemon/agents.js [hunk 1]
```diff
@@ -26,6 +33,10 @@ export const AGENT_DEFS = [
       'stream-json',
       '--verbose',
       '--include-partial-messages',
+      // No interactive approval surface in the web UI; the daemon already
+      // sandboxes the agent to the project's cwd, so let it write freely.
+      '--permission-mode',
+      'bypassPermissions',
```
Comment (lefarcen) [inline daemon/agents.js]: `bypassPermissions` is the strongest of Claude Code's four modes — it skips every permission check, including the cwd-escape guard (`acceptEdits` would still write freely inside cwd but block writes outside). Given the daemon already pins cwd to `.od/projects/<id>/` and `isSafeId` rejects traversal, the marginal blast radius is bounded; still, `acceptEdits` would give you defense-in-depth essentially for free if you ever ship a misconfigured project id. Not blocking — just worth weighing.

File: daemon/agents.js [hunk 2]
```diff
@@ -34,15 +45,17 @@ export const AGENT_DEFS = [
     name: 'Codex CLI',
     bin: 'codex',
     versionArgs: ['--version'],
-    buildArgs: (prompt) => ['exec', prompt],
+    // `--full-auto` = workspace-write sandbox + auto-approve, the closest
+    // match to "trusted local daemon" without dropping the OS-level sandbox.
+    buildArgs: (prompt) => ['exec', '--full-auto', prompt],
```
Comment (lefarcen) [inline daemon/agents.js]: Good call picking `--full-auto` over `--dangerously-bypass-approvals-and-sandbox` — the OS-level workspace-write sandbox stays on, so Codex itself enforces the cwd boundary even if the daemon ever regresses. One footgun: `--full-auto` still escalates to an approval prompt on commands the sandbox flags as needing network or out-of-workspace writes (e.g. `npm install`, `git push`). For an HTML/CSS design surface that's fine, but if a skill ever shells out for deps the stream will hang silently. Worth a one-line note in the doc comment, or a follow-up to surface a daemon-side timeout.

File: daemon/agents.js [hunk 3]
```diff
@@ -34,15 +45,17 @@ export const AGENT_DEFS = [
...
     streamFormat: 'plain',
   },
   {
     id: 'gemini',
     name: 'Gemini CLI',
     bin: 'gemini',
     versionArgs: ['--version'],
-    buildArgs: (prompt) => ['-p', prompt],
+    buildArgs: (prompt) => ['--yolo', '-p', prompt],
```
Comment (lefarcen) [inline daemon/agents.js]: `--yolo` on Gemini CLI is roughly equivalent to Claude's `bypassPermissions` — it auto-approves shell, write, and MCP tools globally, not just in cwd. The intermediate option `--approval-mode=auto_edit` only auto-approves edits and still prompts for shell commands; for a write-files-to-disk surface you probably want at least edits auto-approved, and `--yolo` is the only flag that survives Gemini's MCP tool calls without prompting. So this is the right pick, but the comment block above could note that the cwd sandbox is the *only* line of defense for Gemini (no OS-level sandbox like Codex).

File: daemon/agents.js [hunk 4]
```diff
@@ -58,15 +71,16 @@ export const AGENT_DEFS = [
     name: 'Cursor Agent',
     bin: 'cursor-agent',
     versionArgs: ['--version'],
-    buildArgs: (prompt) => ['-p', prompt],
+    buildArgs: (prompt) => ['-p', '--force', prompt],
```
Comment (lefarcen) [inline daemon/agents.js]: Argv ordering nit: Cursor Agent expects `-p <prompt>` as adjacent tokens, and `--force` is a global flag — `['-p', '--force', prompt]` will likely be parsed as `-p='--force'` and then `prompt` as a positional, depending on the parser. Safer to write `['--force', '-p', prompt]` (flag first, then the prompt pair). Worth a quick smoke test against a current `cursor-agent` build.

File: daemon/agents.js [hunk 5]
```diff
@@ -58,15 +71,16 @@ export const AGENT_DEFS = [
...
     streamFormat: 'plain',
   },
   {
     id: 'qwen',
     name: 'Qwen Code',
     bin: 'qwen',
     versionArgs: ['--version'],
-    buildArgs: (prompt) => ['-p', prompt],
+    // Qwen Code is a Gemini-CLI fork and inherits the same `--yolo` switch.
+    buildArgs: (prompt) => ['--yolo', '-p', prompt],
```
Comment (lefarcen) [inline daemon/agents.js]: Qwen-Code is indeed a Gemini-CLI fork and `--yolo` is supported, but Qwen has historically lagged on flag parity (e.g. `--approval-mode` was missing for a while). If users hit a Qwen version that doesn't ship `--yolo`, the spawn will exit with a usage error and the stream will surface as 'spawn failed'. Consider gating with a `versionArgs`-driven probe later, or at least documenting the minimum supported version in the comment.

**Review by lefarcen — COMMENTED** [review]
Self-correction on the Claude `--permission-mode` comment (L39):

I suggested `acceptEdits` would give defense-in-depth "essentially for free." That's overstated. Per Claude Code's permission model, `acceptEdits` only auto-accepts **file edit** permissions — other tools (Bash, MCP, WebFetch, etc.) still surface an interactive approval prompt. Since the daemon spawns the CLI without a TTY and the web UI has no approve/deny surface (as the doc-comment in `daemon/agents.js` L18-23 explicitly notes), `acceptEdits` would hang or error on any non-edit tool call the agent tries — which is exactly the failure mode the PR is fixing. `bypassPermissions` is the correct choice here given the constraints; the cwd pin via `ensureProject` + `isSafeId` (`/^[A-Za-z0-9._-]{1,128}$/` in `daemon/projects.js:137`) is the actual sandbox boundary, not the permission flag. Retracting the suggestion.

The other four per-agent comments depend on third-party CLI semantics I can't ground from the repo alone — leaving those as-is.

File: daemon/agents.js (hunk 4 above)
Comment (JoKer049) [reply daemon/agents.js]: Thanks for the careful review — fixed in follow-up commit f4859a3.
Updated Cursor Agent args from `['-p', '--force', prompt]` to `['--force', '-p', prompt]` so `-p <prompt>` stays adjacent and avoids parser ambiguity.
For the other notes:
- Kept Claude `bypassPermissions` (agree with your self-correction: `acceptEdits` would still prompt on non-edit tools in a terminal-less UI).
- Kept Codex `--full-auto` and Gemini/Qwen `--yolo` for now; can follow up with timeout/version-probe hardening separately if maintainers want it.
Appreciate the cross-PR conflict heads-up with #15/#28.

**Comment by lefarcen** [comment]
👋 Thanks @JoKer049 — this is the kind of fix that's hard to spot until you actually try the web UI with each agent. Aligning all four CLIs to non-interactive flags is the right shape. 🙏

The cwd-sandboxing chain (`ensureProject` → `isSafeId`) holds up, so the "safe because cwd-scoped" framing is correct. 🔒

Inline notes (one already retracted via follow-up — the `acceptEdits` suggestion was wrong, it still prompts on Bash/MCP/WebFetch which is the bug you're fixing). Per-CLI nuances on Codex `--full-auto`, Gemini/Qwen `--yolo`, Cursor argv ordering are worth a look but not blocking. ✅

⚠️ Heads-up: PR #15 rewrites `buildArgs` for the same four agents — textual merge conflict will land on whoever ships second.

**Comment by alchemistklk** [comment]
Linking this to the #21 breakdown as **related to #40**.

This PR should improve the non-interactive permission side of the “manual command / sandbox flow” problem. #40 also tracks generated project-file discoverability, so after this PR is updated/merged we’ll verify whether project files appear in Design Files without manual shell commands, or whether a separate maintainer follow-up is still needed for nested/project-relative file discovery.

**Comment by JoKer049** [comment]
Thanks for the detailed follow-up and for retracting the `acceptEdits` suggestion.

@lefarcen  We’ve applied the Cursor argv ordering fix (`--force` before `-p`) and will keep this PR scoped to non-interactive permission handling.  
If #15 lands first, I’ll rebase and resolve the `buildArgs` conflicts accordingly.

Appreciate linking this with #21/#40 — happy to follow up separately if file discoverability still needs maintainer-side changes after merge.

**Review by alchemistklk — COMMENTED** [review]
Decision: request rebase for #40-related review.

I verified this branch against current `origin/main` and it has a real content conflict in `daemon/agents.js`. The branch is also based on the older agent definitions, so the current diff would drop newer main behavior around fallback model lists, model discovery, reasoning options, and extra agent argument handling if resolved mechanically.

Please rebase onto latest `main` and preserve the current main behavior while threading the non-interactive permission flags into the newer `buildArgs` shape. In particular, keep the model picker / reasoning handling now present around `daemon/agents.js` lines 110-245 on main, then add the relevant non-interactive flags for Claude, Codex, Gemini, Cursor Agent, and Qwen.

Verification run before the merge-conflict check:
- `npm install` passed, with existing audit warnings.
- `npm run typecheck` passed.
- `npm run build` passed.

Related to #40, but #40 should remain open until generated/project-file discoverability is verified separately.

**Review by alchemistklk — APPROVED** [review]
Decision update: approve current head `a29c145` as the #40-related non-interactive permission improvement.

The previous rebase request was based on the earlier head (`f4859a3`) before the conflict-resolution commit landed. I re-reviewed the live PR head after the update: it now merges cleanly with current `origin/main`, keeps the current model picker / fallback model / Codex reasoning behavior, and threads the permission flags into the newer `buildArgs` shapes.

Verification on current head:
- `git merge --no-commit --no-ff origin/main` reported already up to date.
- `npm install` passed, with the repo engine warning under local Node v25.9.0 and existing audit warnings.
- `npm run typecheck` passed.
- `npm run build` passed.

Related to #40, but #40 should remain open until generated/project-file discoverability is verified separately.

**Comment by JoKer049** [comment]
> Decision: request rebase for #40-related review.
> 
> I verified this branch against current `origin/main` and it has a real content conflict in `daemon/agents.js`. The branch is also based on the older agent definitions, so the current diff would drop newer main behavior around fallback model lists, model discovery, reasoning options, and extra agent argument handling if resolved mechanically.
> 
> Please rebase onto latest `main` and preserve the current main behavior while threading the non-interactive permission flags into the newer `buildArgs` shape. In particular, keep the model picker / reasoning handling now present around `daemon/agents.js` lines 110-245 on main, then add the relevant non-interactive flags for Claude, Codex, Gemini, Cursor Agent, and Qwen.
> 
> Verification run before the merge-conflict check:
> 
> * `npm install` passed, with existing audit warnings.
> * `npm run typecheck` passed.
> * `npm run build` passed.
> 
> Related to #40, but #40 should remain open until generated/project-file discoverability is verified separately.

Done — rebased/merged latest `main` and resolved `daemon/agents.js` conflict while preserving current main model-picker/reasoning/fallback behavior, then threaded the non-interactive flags into the new `buildArgs` shape.
Latest commit: `a29c145`. Please re-check.

**Review by lefarcen — APPROVED** [review]
LGTM on the substance ✅ — non-interactive flags are the right call for a no-TTY web UI, and the cwd-sandboxing chain (`ensureProject` → `isSafeId` → `path.join`) holds up, so the safety framing checks out. 🔒

⚠️ Merge-order suggestion: please rebase **after #15 lands** — it reshapes `buildArgs` for the same four agents, so `--full-auto` / `--yolo` / `--force` will need re-threading into the new stdin argv shape. Substance-wise nothing else is blocking. 🚀

**Comment by leilei926524-tech** [comment]
Hi @JoKer049 — welcome to Open Design contributors. 🎉

Your first merged PR (#26) just landed — that puts you in a small group of people who've actually shipped code into OD. We have a Discord **#contributors** channel where the rest of the crew hangs out, and we'd love for you to drop in:

**👉 https://discord.gg/3C6EWXbdQQ**

Why it's worth joining:
- **Faster PR feedback** — maintainers are around in Discord throughout the day, review pings turn around in hours
- **First look at updates** — release notes and behavior changes before they hit GitHub
- **Skills & templates** — community-built skills and design templates, easy to grab
- **Real user showcases** — see what people are actually building with OD
- **A direct line to the team** — for anything that doesn't fit a GitHub thread

Hope to see you there. If you're looking for a second issue to pick up, the `good first issue` and `help wanted` labels are a good place to scan.
