### PR TITLE
fix(daemon): support Claude Code CLI <1.0.86 (avoid --include-partial-messages, parse assistant wrapper text)

### LINKED ISSUE #33: Empty assistant output on Claude Code CLI <1.0.86 (and --include-partial-messages spawn crash)
## Summary

On older Claude Code CLI installs (`claude` <1.0.86), the daemon either crashes the chat at spawn time or silently drops the entire assistant response — UI shows `Done · N out · $X` with an empty bubble.

Two coupled defects:

1. **Spawn crash on flag mismatch.** `daemon/agents.js` unconditionally passes `--include-partial-messages` to `claude`. That flag was added in 1.0.86. Older binaries (e.g. a 1.0.84 install resolved earlier on PATH) reject it:

   ```
   agent exited with code 1
   error: unknown option '--include-partial-messages'
   ```

2. **Empty output even after dropping the flag.** `daemon/claude-stream.js` only extracted assistant text from `stream_event.content_block_delta.text_delta` events — these are only emitted *with* `--include-partial-messages`. Without it, older builds emit the full text in the `assistant` wrapper (`message.content[].type === 'text'`), but the parser's `assistant` branch only pulled out `tool_use` blocks and ignored text. Net result: tokens billed, output dropped.

## Repro

1. Have Claude Code CLI <1.0.86 first on `PATH` (any older global or nested vendor install).
2. `pnpm dev:all`
3. Send any chat. Either the stream errors instantly, or — after manually removing the flag — completes with `Done · N tokens` and an empty assistant message.

## Environment

- Repo: `nexu-io/open-design`
- Daemon-resolved `claude`: `1.0.84 (Claude Code)`
- OS: macOS (darwin)
- Node: 18+

## Fix

PR follows. Probe `claude --help` at agent-detection time, gate flags on detected capabilities, and parse text from the `assistant` wrapper as a fallback (deduped via a per-message-id `textStreamed` set so newer streams don't double-emit).

### PR DESCRIPTION
**Pull request by lukebaze**
## Summary

Two coupled bugs surfaced when the daemon resolved an older `claude` binary on PATH (e.g. `1.0.84`):

1. **Spawn crashed** with `unknown option '--include-partial-messages'` — that flag landed in 1.0.86 and we passed it unconditionally.
2. **Empty assistant bubble** even after dropping the flag — the stream parser only extracted text from `stream_event.content_block_delta.text_delta` events, which only fire under `--include-partial-messages`. The full text in the `assistant` wrapper went unread; UI showed `Done · N out · $X` with no content.

## Fix

- `daemon/agents.js` — probe `claude --help` once at agent detection, cache advertised flags in a module-level `agentCapabilities` map, and gate `--include-partial-messages` / `--add-dir` on the probe. Safe baseline (no optional flags) when probing fails.
- `daemon/server.js` — warm the cache on startup so the first `/api/chat` doesn't race ahead of the frontend's `/api/agents` call.
- `daemon/claude-stream.js` — parse `text` and `thinking` blocks out of the `assistant` wrapper as a fallback, deduped via a per-message-id `textStreamed` set so newer builds streaming deltas never double-emit.

## Test plan

- [x] `pnpm typecheck` — clean.
- [x] Unit-style replay: 1.0.84-shape stream → single `text_delta` emitted; partial-messages stream → deltas only, no duplication from assistant wrapper.
- [x] Live `/api/chat` with daemon-resolved 1.0.84: SSE now carries `event: agent` → `{"type":"text_delta","delta":"pong"}` to the UI.
- [x] Capability probe verified against both real binaries (1.0.84 advertises no flag → omitted; 2.1.123 advertises it → included).
- [x] Spawn no longer crashes with `unknown option`.

Closes #33.

### CODE REVIEW

File: daemon/agents.js [hunk 1]
```diff
@@ -24,19 +31,34 @@ export const AGENT_DEFS = [
...
+      if (caps.partialMessages) {
+        args.push('--include-partial-messages');
+      }
       const dirs = (extraAllowedDirs || []).filter(
         (d) => typeof d === 'string' && d.length > 0,
       );
-      if (dirs.length > 0) {
+      // `--add-dir` is older but still gate it for symmetry — old/forked
+      // builds may lack it.
+      if (dirs.length > 0 && caps.addDir !== false) {
```
Comment (lefarcen) [inline daemon/agents.js:128]: Asymmetric with the `partialMessages` gate above: when the probe failed or hasn't run, `caps.addDir` is `undefined`, and `undefined !== false` is `true` — so `--add-dir` *is* passed. That contradicts the file-top comment that says caps default to off as a safe baseline, and means a forked/old build without `--add-dir` would still get the flag. Suggest `caps.addDir === true` for parity with `if (caps.partialMessages)`.

File: daemon/agents.js [hunk 2]
```diff
@@ -110,11 +132,29 @@ async function probe(def) {
...
+        maxBuffer: 4 * 1024 * 1024,
+      });
+      for (const [flag, key] of Object.entries(def.capabilityFlags)) {
+        caps[key] = stdout.includes(flag);
+      }
+    } catch {
+      // If --help fails, leave caps empty — buildArgs falls back to the safe
+      // baseline (no optional flags).
+    }
+    agentCapabilities.set(def.id, caps);
```
Comment (lefarcen) [inline daemon/agents.js:393]: Probe runs once at startup and is never refreshed. If the user upgrades Claude Code mid-session (e.g. `npm i -g @anthropic-ai/claude-code` in another terminal), the daemon will keep omitting `--include-partial-messages` until restart. Worth either re-probing on a TTL or invalidating when `getAgentDef` is hit and the resolved version differs from the cached one.

**Review by lefarcen — COMMENTED** [review]
Solid, well-scoped fix for #33: the two failure modes (spawn crash on `--include-partial-messages`, empty bubble on the older wrapper-only path) are diagnosed correctly and addressed at the right layers. Capability probe + dedup-via-`textStreamed` is the right shape.

A few small concerns left inline: the `--add-dir` gate is inverted vs the documented safe baseline, the warm probe is fire-and-forget so a fast first `/api/chat` after boot can race ahead of it, and the `assistant`-wrapper dedup uses `obj.message.id` rather than the tracked `currentMessageId`. None are blocking.

File: daemon/agents.js [hunk 3]
```diff
@@ -110,11 +132,29 @@ async function probe(def) {
...
+    try {
+      const { stdout } = await execFileP(resolved, def.helpArgs, {
+        timeout: 5000,
+        maxBuffer: 4 * 1024 * 1024,
+      });
+      for (const [flag, key] of Object.entries(def.capabilityFlags)) {
+        caps[key] = stdout.includes(flag);
+      }
+    } catch {
+      // If --help fails, leave caps empty — buildArgs falls back to the safe
```
Comment (lefarcen) [inline daemon/agents.js:390]: On `--help` failure the catch leaves `caps = {}`, which is then `set()` and indistinguishable from "probe ran and the binary advertises nothing". Consider storing a sentinel (e.g. `caps.__probed = true` only on success) so a future retry path can tell "never probed" from "probed empty".

File: daemon/server.js [hunk 4]
```diff
@@ -99,6 +99,11 @@ export async function startServer({ port = 7456 } = {}) {
   app.use(express.json({ limit: '4mb' }));
   const db = openDatabase(PROJECT_ROOT);
 
+  // Warm agent-capability probes (e.g. whether the installed Claude Code
+  // build advertises --include-partial-messages) so the first /api/chat
+  // hits a populated cache even if /api/agents hasn't been called yet.
+  void detectAgents().catch(() => {});
```
Comment (lefarcen) [inline daemon/server.js:112]: Fire-and-forget warm-up: `/api/chat` doesn't await this, and `--help` has a 5s timeout. A user who fires off a chat within ~hundreds of ms of daemon boot (common in dev with `pnpm dev:all` + auto-reconnect) will hit `caps = {}` and silently lose `--include-partial-messages` on a *new* CLI — degrading UX to the older wrapper-only path. Either await before `app.listen`, or have `/api/chat` lazily `await detectAgents()` once before `def.buildArgs`.

File: daemon/claude-stream.js [hunk 5]
```diff
@@ -85,9 +93,14 @@ export function createClaudeStreamHandler(onEvent) {
...
     // content block. For tool_use blocks whose input finished assembling,
-    // emit tool_use now with the final parsed input.
+    // emit tool_use now with the final parsed input. For text blocks, emit
+    // the text as a single delta — but only if no streaming deltas already
+    // covered it (older Claude Code without --include-partial-messages
+    // delivers text only here; newer builds stream it and would duplicate).
     if (obj.type === 'assistant' && obj.message?.content) {
       currentMessageId = obj.message.id ?? currentMessageId;
+      const msgId = obj.message.id ?? null;
+      const alreadyStreamed = msgId ? textStreamed.has(msgId) : false;
```
Comment (lefarcen) [inline daemon/claude-stream.js:103]: Reads `obj.message.id` directly and falls back to `false` when null, but the streaming path keys dedup on `currentMessageId` (set from `message_start`). If an `assistant` wrapper arrives without an `id`, `alreadyStreamed` is `false` even when deltas already ran for the active message — and the wrapper text re-emits, duplicating. Safer: `const msgId = obj.message.id ?? currentMessageId;` before the `has()` check.

File: daemon/claude-stream.js [hunk 6]
```diff
@@ -26,6 +27,13 @@ export function createClaudeStreamHandler(onEvent) {
   // Most recent assistant message id so content_block_* events without an id
   // can be attributed correctly.
   let currentMessageId = null;
+  // Message ids that already streamed text via `stream_event` deltas.
+  // When `--include-partial-messages` is OFF (older Claude Code, e.g. 1.0.84
+  // pre-flag), no deltas arrive — only the final `assistant` wrapper carries
+  // text. The fallback below emits that text once, but we must skip it for
+  // newer builds that already streamed deltas, otherwise the message would
+  // duplicate.
+  const textStreamed = new Set();
```
Comment (lefarcen) [inline daemon/claude-stream.js:36]: Minor: this `Set` grows for the lifetime of the handler and is never pruned. Per-`/api/chat` it's bounded, but multi-turn sessions on the new path can accumulate message ids unboundedly. Once a message's `assistant` wrapper has been processed (or `result` arrives), the id can be `delete()`d — keeps memory flat over long chats.

**Review by lefarcen — COMMENTED** [review]
**Self-correction on three of my earlier inline comments — please disregard them.**

I re-read `daemon/agents.js` and `daemon/server.js` after submitting and got two of the concerns wrong:

1. **`daemon/agents.js:151` — "probe is never refreshed".** Wrong. `detectAgents()` is called from `GET /api/agents` (`daemon/server.js:381`), and `probe()` unconditionally re-runs `execFileP(resolved, def.helpArgs, ...)` and re-`set()`s `agentCapabilities`. So the cache *does* refresh every time the frontend hits `/api/agents` — which it does on settings open / app load. The mid-session-CLI-upgrade scenario I described is therefore not a real bug; the next `/api/agents` call picks up the new flags. Please ignore that comment.

2. **`daemon/claude-stream.js:36` — `textStreamed` Set growth.** Overstated. `createClaudeStreamHandler` is invoked per `/api/chat` request and the handler is short-lived; the Set is bounded by message-ids inside a single chat turn (usually 1–2). Not an unbounded-growth concern. The `delete()` suggestion is fine to ignore.

3. **`daemon/agents.js:148` — "can't distinguish probe-failed from probed-empty".** Technically true but practically irrelevant: `buildArgs` treats `caps.x === undefined` and `caps.x === false` identically (both skip the flag). The sentinel suggestion would only matter if a future retry path is added, which doesn't exist today. Premature. Ignore.

The other three concerns still stand:
- `daemon/agents.js:61` — `--add-dir` gate is asymmetric with the `partialMessages` gate (`undefined !== false === true` lets it pass on empty caps).
- `daemon/server.js:105` — startup warm probe is fire-and-forget and a `/api/chat` arriving in the boot race window will see empty caps. Awaiting before `app.listen` (or lazy-init in `/api/chat`) closes the window.
- `daemon/claude-stream.js:103` — `msgId` re-derives from `obj.message.id` instead of using the `currentMessageId` already updated on the previous line. Trivial drop-in.

Apologies for the noise.

**Comment by alchemistklk** [comment]
Thanks for the fix. The direction looks right: gating `--include-partial-messages` and parsing completed `assistant.message.content[].text` should address #33.

Before merge, could you please handle two things?

1. Rebase this branch onto latest `main`.

GitHub currently reports this PR as not mergeable. `daemon/agents.js` has changed on `main` for the model picker, fallback models, live model cache, and per-agent model/reasoning options. Please keep those newer paths when resolving the conflict.

2. Tighten the `--add-dir` capability gate.

Right now this condition still passes `--add-dir` when capability probing has not run or `claude --help` fails:

```js
if (dirs.length > 0 && caps.addDir !== false)
```

That conflicts with the stated safe baseline of “no optional flags” when probing fails. I think this should require positive detection:

```js
if (dirs.length > 0 && caps.addDir) {
  args.push(`--add-dir`, ...dirs);
}
```

The stream parser fallback itself looks good to me. After the rebase and `--add-dir` adjustment, please rerun:

```bash
npm run typecheck
npm run build
```

**Comment by lefarcen** [comment]
👋 Thanks @lukebaze — really nice diagnosis here. Pinpointing that `--include-partial-messages` *and* the wrapper-only fallback were two coupled regressions, then verifying against both 1.0.84 and 2.1.123 binaries, is exactly the level of receipts that makes the fix easy to trust. 🙏

Already left technical thoughts inline (and a self-correction retracting three of them that didn't pan out on a closer read of `detectAgents`). The remaining three (`--add-dir` gate symmetry, warm-probe race window, `msgId` re-derivation) are minor — happy to merge as-is if you'd rather defer them. ✅

**Review by lefarcen — APPROVED** [review]
LGTM ✅ — diagnosis is solid, fix shape is right (capability probe + wrapper-text fallback). The three remaining inline nits (`--add-dir` gate symmetry, warm-probe race window, `msgId` re-derivation) are non-blocking robustness items — happy to see this land as-is and address them as a small follow-up if at all. 🚀

**Comment by lefarcen** [comment]
Hi @lukebaze! 🎉

Thanks for the contribution — this is a really thorough fix for the Claude Code version compatibility issue! The backward-compat probe + fallback parsing pattern is exactly the right approach.

I will run a deep review and get back to you within 24h.

Join our community while you wait:
- Feishu: https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=90emc2e9-86cd-4723-b455-ca41b70f162d
- Discord: https://discord.gg/nexu

Thanks for making open-design better!
— open-design team

File: daemon/agents.js [hunk 7]
```diff
@@ -89,21 +103,29 @@ export const AGENT_DEFS = [
...
+        args.push('--include-partial-messages');
+      }
       if (options.model && options.model !== 'default') {
         args.push('--model', options.model);
       }
       const dirs = (extraAllowedDirs || []).filter(
         (d) => typeof d === 'string' && d.length > 0,
       );
-      if (dirs.length > 0) {
+      // `--add-dir` is older but still gate it for symmetry — old/forked
```
Comment (lefarcen) [inline daemon/agents.js:126]: **P1** Race condition / incorrect logic: `caps.addDir !== false` is wrong. The capability map only sets keys to `true` when detected, leaving them `undefined` when not found. Since `undefined !== false` evaluates to `true`, this will pass `--add-dir` even when the flag wasn't detected in help output, causing spawn failures on old builds that lack it.

**Fix**: Change to `caps.addDir === true` (matching the `partialMessages` check above).

File: daemon/claude-stream.js [hunk 8]
```diff
@@ -153,10 +180,12 @@ export function createClaudeStreamHandler(onEvent) {
       const delta = ev.delta;
 
       if (delta.type === 'text_delta' && typeof delta.text === 'string') {
+        if (currentMessageId) textStreamed.add(currentMessageId);
```
Comment (lefarcen) [inline daemon/claude-stream.js:183]: **P1** Deduplication timing bug: `textStreamed.add(currentMessageId)` happens AFTER `onEvent()` emits the delta. If a message somehow receives both a delta event and the wrapper text in rapid succession (edge case, but possible with buffering/timing), the first delta won't be marked as streamed until after emission, allowing a duplicate to slip through.

**Fix**: Move both `textStreamed.add()` calls (lines 183 and 188) to BEFORE their respective `onEvent()` calls.

File: daemon/agents.js [hunk 9]
```diff
@@ -352,6 +374,24 @@ async function probe(def) {
...
+    const caps = {};
+    try {
+      const { stdout } = await execFileP(resolved, def.helpArgs, {
+        timeout: 5000,
+        maxBuffer: 4 * 1024 * 1024,
+      });
+      for (const [flag, key] of Object.entries(def.capabilityFlags)) {
+        caps[key] = stdout.includes(flag);
+      }
+    } catch {
```
Comment (lefarcen) [inline daemon/agents.js:389]: **P2** Fragile string matching: `stdout.includes(flag)` will false-positive if help output mentions the flag in an example, error message, or deprecation notice (e.g., 'Warning: --include-partial-messages is deprecated'). This could cause the daemon to pass a flag that's actually unavailable.

**Fix**: Use regex matching on actual option lines: `const flagRegex = new RegExp(\`^\\s*\${flag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\`, 'm'); caps[key] = flagRegex.test(stdout);`

File: daemon/agents.js [hunk 10]
```diff
@@ -352,6 +374,24 @@ async function probe(def) {
...
+      // If --help fails, leave caps empty — buildArgs falls back to the safe
```
Comment (lefarcen) [inline daemon/agents.js:390]: **P2** Silent probe failure: The catch block leaves `caps` empty without logging. When help output changes or the binary behaves unexpectedly, debugging becomes painful because there's no trace of what failed.

**Fix**: Add debug/warn logging: `catch (err) { console.warn(\`Agent \${def.id} help probe failed:\`, err.message); }`

File: daemon/server.js [hunk 11]
```diff
@@ -106,6 +106,11 @@ export async function startServer({ port = 7456 } = {}) {
...
```
Comment (lefarcen) [inline daemon/server.js:112]: **P2** Swallowed startup errors: `void detectAgents().catch(() => {})` silently swallows all probe errors. If probing crashes (bad PATH, permission issue, missing binary), the first `/api/chat` will hit an empty capability map and fail with cryptic 'unknown option' errors that look like a Claude Code bug, not a config issue.

**Fix**: At minimum, log the error: `.catch(err => console.warn('Agent probe warming failed:', err))`. Consider whether the daemon should fail-fast if zero agents are detected (depends on product requirements — can open-design run without any agents?).

File: daemon/agents.js [hunk 12]
```diff
@@ -89,21 +103,29 @@ export const AGENT_DEFS = [
       { id: 'claude-haiku-4-5', label: 'claude-haiku-4-5' },
     ],
     buildArgs: (prompt, _imagePaths, extraAllowedDirs = [], options = {}) => {
```
Comment (lefarcen) [inline daemon/agents.js:105]: **P3** Implicit race contract: `buildArgs` now reads from `agentCapabilities`, but there's no guarantee `probe()` has run first. The code assumes 'fallback to safe baseline' but doesn't document what happens if a user hits `/api/chat` before `/api/agents`. The `server.js` warming mitigates this, but the contract is subtle.

**Suggestion**: Add a comment here clarifying the race: `// Capability map is populated by probe() (called on /api/agents or warmed at startup). If buildArgs runs before probing completes, caps will be empty and we fall back to the safe baseline (no optional flags).`

File: daemon/claude-stream.js [hunk 13]
```diff
@@ -85,9 +93,14 @@ export function createClaudeStreamHandler(onEvent) {
...
     // `assistant` messages are the "block finished" signal for the current
     // content block. For tool_use blocks whose input finished assembling,
-    // emit tool_use now with the final parsed input.
+    // emit tool_use now with the final parsed input. For text blocks, emit
+    // the text as a single delta — but only if no streaming deltas already
+    // covered it (older Claude Code without --include-partial-messages
+    // delivers text only here; newer builds stream it and would duplicate).
     if (obj.type === 'assistant' && obj.message?.content) {
       currentMessageId = obj.message.id ?? currentMessageId;
+      const msgId = obj.message.id ?? null;
```
Comment (lefarcen) [inline daemon/claude-stream.js:102]: **P3** Variable naming: `alreadyStreamed` is computed once per `assistant` message but checked per block. If the message has multiple text blocks (rare per Claude API but possible), all blocks inherit the same flag. Likely correct, but the name suggests block-level scope.

**Suggestion**: Rename to `messageAlreadyStreamed` for clarity.

**Review by lefarcen — CHANGES_REQUESTED** [review]
Hey @lukebaze! 🎉

Thanks for tackling this compatibility issue — the backward-compat probe + fallback parsing pattern is exactly the right architecture. The test plan is thorough and the fix clearly solves both bugs.

Found 2 critical logic bugs that will cause the feature to break under certain conditions (P1), plus a few robustness issues (P2) and nits (P3). Details inline below.

**Comment by lefarcen** [comment]
**Post-merge note**: This PR was merged before the review completed. The review above identified 2 P1 bugs that should be addressed in a follow-up:

1. **agents.js:126** - `caps.addDir !== false` will incorrectly pass `--add-dir` even when not detected (should be `=== true`)
2. **claude-stream.js:183,188** - Deduplication tracking happens after emission, risking duplicates in edge cases (should track before emitting)

The P2/P3 issues are non-critical but would improve robustness. 

@lukebaze if you'd like to address these in a follow-up PR, that would be great! Otherwise we can handle it internally. Thanks again for the contribution! 🎉

**Comment by lukebaze** [comment]
thanks @lefarcen , i'm glad to be a part of open-design comm!

**Comment by lefarcen** [comment]
Welcome aboard, @lukebaze! 🎉 We're excited to have you here. Your contributions are already making a difference — looking forward to seeing more from you. Feel free to jump into any issue that catches your eye!

If you need anything, the community is here to help:
- Feishu: https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=90emc2e9-86cd-4723-b455-ca41b70f162d
- Discord: https://discord.gg/nexu

Happy coding! 🚀
— open-design team

**Comment by leilei926524-tech** [comment]
Hi @lukebaze — welcome to Open Design contributors. 🎉

Your first merged PR (#34) just landed — that puts you in a small group of people who've actually shipped code into OD. We have a Discord **#contributors** channel where the rest of the crew hangs out, and we'd love for you to drop in:

**👉 https://discord.gg/3C6EWXbdQQ**

Why it's worth joining:
- **Faster PR feedback** — maintainers are around in Discord throughout the day, review pings turn around in hours
- **First look at updates** — release notes and behavior changes before they hit GitHub
- **Skills & templates** — community-built skills and design templates, easy to grab
- **Real user showcases** — see what people are actually building with OD
- **A direct line to the team** — for anything that doesn't fit a GitHub thread

Hope to see you there. If you're looking for a second issue to pick up, the `good first issue` and `help wanted` labels are a good place to scan.
