### PR TITLE
Fix document previews for uploaded files

### LINKED ISSUE #38: Fix garbled preview for uploaded document files
Parent: #21

## Problem

Users report that uploaded documents can display as garbled text in the file viewer.

## Root cause hypothesis

The app needs stricter file-kind classification and preview behavior for binary/document formats. Office/PDF-style files should not be decoded as source text unless we have a real renderer for that format.

## Expected behavior

- Uploaded .docx, .pptx, .xlsx, .pdf and other binary documents should not render as mojibake text.
- Unsupported document formats should show a clear binary/document viewer with Open and Download actions.
- Text/code viewers should only be used for formats that are safe to decode as text.

## Verification

- Upload .docx, .pptx, .pdf, .md, and .txt files.
- Confirm binary documents show document/binary actions instead of garbled text.
- Confirm .md and .txt still render as readable text.

Part of #21.

### PR DESCRIPTION
**Pull request by alchemistklk**
## Summary
- classify uploaded PDF, DOCX, PPTX, and XLSX files as previewable document types instead of generic binary
- add a local preview endpoint for document files, including OOXML text extraction and PDF text extraction fallback
- render readable previews in the file viewer while keeping Open and Download actions available

Closes #38

## Verification
- npm run typecheck
- npm run build
- API smoke checks for DOCX, PPTX, XLSX preview JSON and unsupported binary 415 response
- Browser smoke test with sample.pdf, sample.docx, sample.pptx, sample.xlsx, sample.md, and sample.txt on localhost:5174

### CODE REVIEW

File: daemon/document-preview.js [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+  }
+  return {
+    kind,
+    title: path.basename(file.name),
+    sections: await previewXlsx(zip),
+  };
+}
+
+async function previewPdf(buffer) {
+  const tmp = await import('node:os').then(({ tmpdir }) =>
```
Comment (lefarcen) [inline daemon/document-preview.js]: P1 **Temp file race condition + predictable path vulnerability.** The temp path uses `Date.now()` + weak `Math.random()` which creates a TOCTOU race window:

1. Attacker can predict the path and create a symlink before `writeFile` executes
2. Multiple concurrent requests with identical timestamps will collide
3. PDF processing will follow symlinks, potentially writing user-controlled data to arbitrary paths

**Fix:** Use `fs.promises.mkdtemp()` to create an unpredictable directory, then write inside it:
```js
const { mkdtemp, writeFile, rm } = await import('node:fs/promises');
const tmpDir = await mkdtemp(path.join(tmpdir(), 'od-preview-'));
const tmpFile = path.join(tmpDir, 'input.pdf');
await writeFile(tmpFile, buffer);
try {
  const { stdout } = await execFileP('pdftotext', ['-layout', tmpFile, '-'], ...);
  ...
} finally {
  rm(tmpDir, { recursive: true, force: true }).catch(() => {});
}
```

File: daemon/document-preview.js [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+    path.join(tmpdir(), `od-preview-${Date.now()}-${Math.random().toString(36).slice(2)}.pdf`),
+  );
+  const { writeFile, unlink } = await import('node:fs/promises');
+  await writeFile(tmp, buffer);
+  try {
```
Comment (lefarcen) [inline daemon/document-preview.js:61]: P1 **Command injection via buffer content.** While `execFileP` is safer than `exec`, the `pdftotext` binary itself may be vulnerable to malicious PDF payloads (e.g., crafted streams that exploit parser bugs). The 5s timeout helps but doesn't prevent:

1. Fork bombs / resource exhaustion (user uploads 100 PDFs in parallel)
2. pdftotext segfaults leaking temp file handles
3. No rate limiting per-user

**Mitigations:**
- Add per-user concurrency limit (e.g., `p-limit` with limit=2 per projectId)
- Wrap `execFileP` in a resource group with ulimit (max 512MB RSS, no child processes)
- Log + alert on repeated crashes: `if (stderr.includes('Segmentation fault')) { metrics.increment('pdf.crashes') }`

File: daemon/document-preview.js [hunk 3]
```diff
@@ -0,0 +1,227 @@
...
+  }
+
+  if (kind === 'pdf') {
+    return {
+      kind,
+      title: path.basename(file.name),
+      sections: await previewPdf(file.buffer),
+    };
+  }
+
```
Comment (lefarcen) [inline daemon/document-preview.js:31]: P1 **Zip bomb / XXE DoS.** `JSZip.loadAsync(file.buffer)` will decompress the entire archive into memory with no size limit. A malicious 10MB DOCX can expand to 10GB of XML, crashing the daemon.

**Fix:** Check uncompressed size before loading:
```js
const zip = await JSZip.loadAsync(file.buffer);
let totalUncompressed = 0;
for (const name of Object.keys(zip.files)) {
  totalUncompressed += zip.files[name]._data?.uncompressedSize ?? 0;
  if (totalUncompressed > 50 * 1024 * 1024) { // 50MB limit
    const err = new Error('document too large to preview');
    err.statusCode = 413;
    throw err;
  }
}
```

Alternatively, use streaming decompression with `jszip-stream` or reject files >5MB at upload time.

File: daemon/document-preview.js [hunk 4]
```diff
@@ -0,0 +1,227 @@
...
+  for (const m of raw.matchAll(/([\w:-]+)="([^"]*)"/g)) {
+    attrs[m[1]] = decodeXml(m[2]);
+  }
+  return attrs;
+}
+
+function extractFirst(raw, pattern) {
+  const m = raw.match(pattern);
+  return m ? m[1] ?? '' : '';
+}
```
Comment (lefarcen) [inline daemon/document-preview.js:228]: P2 **XML entity expansion (billion laughs attack).** The regex-based XML parsing doesn't sanitize entity references. A malicious DOCX with:
```xml
<!DOCTYPE lol [
  <!ENTITY lol0 "lol">
  <!ENTITY lol1 "&lol0;&lol0;&lol0;...">
  ...
  <!ENTITY lol9 "&lol8;&lol8;&lol8;...">
]>
<w:p><w:t>&lol9;</w:t></w:p>
```
will cause `decodeXml` to hang/OOM when the entity expands exponentially.

**Fix:** Use a proper XML parser (e.g., `fast-xml-parser` with `ignoreAttributes: false, parseTagValue: false`) or reject documents containing `<!ENTITY` declarations upfront:
```js
if (xml.includes('<!ENTITY')) {
  const err = new Error('unsupported XML entities');
  err.statusCode = 415;
  throw err;
}
```

File: daemon/server.js [hunk 5]
```diff
@@ -731,6 +732,17 @@ export async function startServer({ port = 7456 } = {}) {
     }
   });
 
+  app.get('/api/projects/:id/files/:name/preview', async (req, res) => {
```
Comment (lefarcen) [inline daemon/server.js:735]: P2 **Missing input validation.** The endpoint doesn't validate `req.params.name` before passing to `readProjectFile`. If `name` contains path traversal sequences (`../../../etc/passwd`), the file read will escape the project directory (though `readProjectFile` may already sanitize — verify this).

**Check:** Does `readProjectFile` in `projects.js` call `path.resolve()` and verify the result is still under `PROJECTS_DIR`? If not, add:
```js
const safeName = path.basename(req.params.name); // strip any path components
const file = await readProjectFile(PROJECTS_DIR, req.params.id, safeName);
```

**Review by lefarcen — CHANGES_REQUESTED** [review]
Hey @alchemistklk! Nice work on the document preview feature — solid OOXML parsing implementation and clean UI integration. Found 3 critical security issues and 2 correctness concerns that need attention before merge.

File: daemon/document-preview.js (hunk 1 above)
Comment (alchemistklk) [reply daemon/document-preview.js]: Fixed in 65b03c3. PDF preview now uses `mkdtemp(path.join(tmpdir(), 'od-preview-'))`, writes `input.pdf` inside that private directory with `flag: 'wx'`, and removes the directory in `finally`.

File: daemon/document-preview.js (hunk 2 above)
Comment (alchemistklk) [reply daemon/document-preview.js:61]: Addressed in 65b03c3 with bounded local preview execution: PDF previews now reject files over 10 MB before invoking `pdftotext`, keep the existing 5s timeout and 2 MB stdout cap, and run through a process-local concurrency limiter of 2. I did not add daemon-level metrics/ulimit in this PR because this repo does not currently have that infrastructure, but the preview path is now bounded for the local daemon use case.

File: daemon/document-preview.js (hunk 3 above)
Comment (alchemistklk) [reply daemon/document-preview.js:31]: Fixed in 65b03c3. OOXML preview now rejects compressed inputs over 10 MB, rejects ZIPs whose total advertised uncompressed size exceeds 50 MB, and rejects individual XML entries over 5 MB before reading them as text.

File: daemon/document-preview.js (hunk 4 above)
Comment (alchemistklk) [reply daemon/document-preview.js:228]: Fixed in 65b03c3. Every XML entry read for preview now goes through `assertSafeXml()`, which rejects `<!DOCTYPE` and `<!ENTITY` payloads with 415 before text extraction/decoding.

File: daemon/server.js (hunk 5 above)
Comment (alchemistklk) [reply daemon/server.js:735]: Verified this is already covered by the shared file API. `readProjectFile()` calls `resolveSafe()`, which validates the project path, rejects absolute/drive/null/`.`/`..` segments, resolves against the project directory, and verifies the resolved path remains under that directory before reading. The new preview endpoint uses that same `readProjectFile()` path.

File: src/components/FileViewer.tsx [hunk 6]
```diff
@@ -801,3 +890,10 @@ function humanSize(bytes: number): string {
   if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
   return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
 }
+
+function documentMetaLabel(file: ProjectFile, t: TranslateFn): string {
+  if (file.kind === 'document') return t('fileViewer.documentMeta');
+  if (file.kind === 'presentation') return t('fileViewer.presentationMeta');
+  if (file.kind === 'spreadsheet') return t('fileViewer.spreadsheetMeta');
+  return t('fileViewer.binaryMeta', { size: humanSize(file.size) });
+}
```
[the remark this answers is not in the document]
Comment (alchemistklk) [reply src/components/FileViewer.tsx:900]: Fixed in 65b03c3. `documentMetaLabel()` now has a dedicated `file.kind === 'pdf'` branch returning `fileViewer.pdfMeta`, so PDF previews show the PDF label and the toolbar appends size only once.

**Review by lefarcen — APPROVED** [review]
All P1 security issues fixed! 🎉

**Verified fixes:**
✅ Temp file race → mkdtemp() + flag:'wx' prevents TOCTOU
✅ Zip bomb → assertZipPreviewSize() caps uncompressed at 50MB
✅ XXE/entity expansion → assertSafeXml() rejects <!ENTITY and <!DOCTYPE
✅ pdftotext DoS → createLimiter(2) caps concurrency + 10MB input size check
✅ Per-entry size → readZipText() checks MAX_XML_ENTRY_BYTES (5MB)

The hardening is comprehensive and the error handling is clean (413/415 status codes). Nice work @alchemistklk!
